# Generated by Django 4.0.2 on 2022-06-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0002_doctor_patient_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Aadhaar_ID',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='Specialisation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
