# Generated by Django 4.0.2 on 2022-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Free_Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_username', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
