# Generated by Django 4.0.2 on 2022-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_slots',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
