# Generated by Django 4.0.2 on 2022-06-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_free_slots_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_slots',
            name='time',
            field=models.TimeField(),
        ),
    ]
