# Generated by Django 4.0.2 on 2022-06-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_free_slots_is_booked_free_slots_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_slots',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='free_slots',
            name='patient_name',
        ),
    ]
